### ISSUE TITLE
{"error":"Invalid origin","code":7} from browser extension

### ISSUE THREAD

**Issue by gergelyszabo94** [csgofloat/CSGOFloat-Inspect#62]
Looks like extension origins are blocked from now on? Is that intentional?
Getting {"error":"Invalid origin","code":7} a response.

**Comment by Rohnlex** [comment]
I'm getting the same error from my extension

**Comment by Step7750** [comment]
Hey,

We were noticing performance degradation in the long lived TCP sockets that Cloudflare was keeping with our origin server and are looking at measures to improve it.

Unfortunately, we've decided to extend our CORS check which originally had the intention of blocking requests within web pages to extensions to see if that helps mitigate the issue.

We may find a better way to handle this and give access again, but request patterns were on the order of magnitude where we think you guys should host CSGFloat yourself :)

Please note that this only affects browsers that try to circumvent CORS, not regular api users. Sorry about the inconvenience!

**Comment by gergelyszabo94** [comment]
@Step7750 thanks for the response, any chance that you might whitelist my extension's URL for a bit while I set up the hosting of csgofloat on my side? 
Also I though more traffic means more data for you and a more complete database of items?

**Comment by Step7750** [comment]
@gergelyszabo94 Yeah, it does, however there is a very high intersection of users between your extension and ours, which effectively makes browsers do duplicate requests and makes the likelihood of queued requests in Chrome higher (max 6 TCP sockets per domain afaik).

We're starting to notice that these measures have caused around 30 million requests to fail in the last 24 hours, so hopefully that can do down, otherwise it does the exact opposite of our intention.

I think what we may do is make it whitelist only and evaluate the situation. I've added your extension to the whitelist (@Rohnlex you can contact me as well for that).

**Comment by gergelyszabo94** [comment]
@Step7750 thank you very much, when do you think I can see the change applied? I will release an update in the coming days that disables float loading by my extension entirely if it detects yours present. And I am prioritizing the switching to self hosted csgofloat as well. (might come to you with some questions regarding that, like how many bot accounts I should use, etc.) Thanks again!

**Comment by Step7750** [comment]
@gergelyszabo94 It seems like your extension doesn't send an origin header because api.csgofloat.com is in the permissions section of the manifest. I've explicitly added it to the whitelist however if it does send the origin header in the future. It also helps us track usage of the API when an origin is set to know when to notify authors in cases of bugs in their software requesting millions of times (had one IP request the same bad thing a couple million times a while back, ugh).

We use around 400 fetching bots, you'll generally want to run the beta branch since that is what prod runs.

For us, we mostly just wanted to tame the API abuse a little bit, so I'll keep your extension on the whitelist indefinitely and you can choose to self-host CSGOFloat if you'd like in the future. I think that'd probably be best to avoid duplicate requests (especially since queued requests in Chrome basically take 1 min+ to resolve from my experience). Keep up the good work on your extension!

**Comment by gergelyszabo94** [comment]
I see, I might need more details on the header thing as I though the origin header was forbidden.

**Comment by Step7750** [comment]
I've decided to revert this change for now since it seems to be causing more failed requests than I anticipated.
