### ISSUE TITLE
Request Timeouts after X float requests

### ISSUE THREAD

**Issue by Squamoto** [csgofloat/CSGOFloat-Inspect#70]
Hey,
For a few days now I get request timeouts all the time after I pulled some item data. It looks like I'm getting rate limited after a certain threshold of requests. I used the standard request delay of 1100ms per bot, but used 10-20 bot accounts which often request 10-20 floats at the same second.
Do I need to get proxies to request floats simultaneously? How many requests can I send at the same time without getting rate limited? Or should I delay the requests and send them out successively? Do you happen to know the thresholds?

Thanks!

**Comment by Step7750** [comment]
Valve had a GC update which had a regression that can timeout requests.

This has been fixed in `beta`, but there are many breaking changes and it isn't ready to be merged to master just yet. If you'd like, you can try contributing a PR porting over the [fix](https://github.com/csgofloat/CSGOFloat-Inspect/pull/51/commits/0cde723b9ab8e814ae17488bb252926bfaf705d9) to `master`.
